DISEASES = {
    'abdominal pain': 39,
    'abnormal menstruation': 101,
    'acidity': 8,
    'acute liver failure': 44,
    'altered sensorium': 98,
    'anxiety': 16,
    'back pain': 37,
    'belly pain': 100,
    'blackheads': 123,
    'bladder discomfort': 89,
    'blister': 129,
    'blood in sputum': 118,
    'bloody stool': 61,
    'blurred and distorted vision': 49,
    'breathlessness': 27,
    'brittle nails': 72,
    'bruising': 66,
    'burning micturition': 12,
    'chest pain': 56,
    'chills': 5,
    'cold hands and feets': 17,
    'coma': 113,
    'congestion': 55,
    'constipation': 38,
    'continuous feel of urine': 91,
    'continuous sneezing': 3,
    'cough': 24,
    'cramps': 65,
    'dark urine': 33,
    'dehydration': 29,
    'depression': 95,
    'diarrhoea': 40,
    'dischromic  patches': 102,
    'distention of abdomen': 115,
    'dizziness': 64,
    'drying and tingling lips': 76,
    'enlarged thyroid': 71,
    'excessive hunger': 74,
    'extra marital contacts': 75,
    'family history': 106,
    'fast heart rate': 58,
    'fatigue': 14,
    'fluid overload': 45,
    'fluid overload.1': 117,
    'foul smell of urine': 90,
    'headache': 31,
    'high fever': 25,
    'hip joint pain': 79,
    'history of alcohol consumption': 116,
    'increased appetite': 104,
    'indigestion': 30,
    'inflammatory nails': 128,
    'internal itching': 93,
    'irregular sugar level': 23,
    'irritability': 96,
    'irritation in anus': 62,
    'itching': 0,
    'joint pain': 6,
    'knee pain': 78,
    'lack of concentration': 109,
    'lethargy': 21,
    'loss of appetite': 35,
    'loss of balance': 85,
    'loss of smell': 88,
    'malaise': 48,
    'mild fever': 41,
    'mood swings': 18,
    'movement stiffness': 83,
    'mucoid sputum': 107,
    'muscle pain': 97,
    'muscle wasting': 10,
    'muscle weakness': 80,
    'nausea': 34,
    'neck pain': 63,
    'nodal skin eruptions': 2,
    'obesity': 67,
    'pain behind the eyes': 36,
    'pain during bowel movements': 59,
    'pain in anal region': 60,
    'painful walking': 121,
    'palpitations': 120,
    'passage of gases': 92,
    'patches in throat': 22,
    'phlegm': 50,
    'polyuria': 105,
    'prominent veins on calf': 119,
    'puffy face and eyes': 70,
    'pus filled pimples': 122,
    'receiving blood transfusion': 111,
    'receiving unsterile injections': 112,
    'red sore around nose': 130,
    'red spots over body': 99,
    'redness of eyes': 52,
    'restlessness': 20,
    'runny nose': 54,
    'rusty sputum': 108,
    'scurring': 124,
    'shivering': 4,
    'silver like dusting': 126,
    'sinus pressure': 53,
    'skin peeling': 125,
    'skin rash': 1,
    'slurred speech': 77,
    'small dents in nails': 127,
    'spinning movements': 84,
    'spotting  urination': 13,
    'stiff neck': 81,
    'stomach bleeding': 114,
    'stomach pain': 7,
    'sunken eyes': 26,
    'sweating': 28,
    'swelled lymph nodes': 47,
    'swelling joints': 82,
    'swelling of stomach': 46,
    'swollen blood vessels': 69,
    'swollen extremeties': 73,
    'swollen legs': 68,
    'throat irritation': 51,
    'toxic look (typhos)': 94,
    'ulcers on tongue': 9,
    'unsteadiness': 86,
    'visual disturbances': 110,
    'vomiting': 11,
    'watering from eyes': 103,
    'weakness in limbs': 57,
    'weakness of one body side': 87,
    'weight gain': 15,
    'weight loss': 19,
    'yellow crust ooze': 131,
    'yellow urine': 42,
    'yellowing of eyes': 43,
    'yellowish skin': 32
}
